/* ============================================================
   MEME-GENICS — pixel.js
   Pixel-art engine + hand-drawn icon atlas.
   Every sprite in the game is a tiny char-grid rendered to a
   cached canvas data-URL and shown with image-rendering:pixelated.
   No emoji. No image files.
   ============================================================ */

const Pixel = {
  INK: '#26203a',
  _cache: new Map(),

  // base palette shared by every grid; per-sprite palettes override/extend
  BASE_PAL: {
    'o': '#26203a',   // outline ink
    'w': '#ffffff',
    'k': '#26203a',
  },

  // add a 1px black outline around every filled region (uniform style)
  INK_RGB: [38, 32, 58],
  outline(ctx, w, h) {
    const img = ctx.getImageData(0, 0, w, h);
    const d = img.data;
    const filled = i => d[i * 4 + 3] > 40;
    const edges = [];
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const i = y * w + x;
        if (filled(i)) continue;
        if ((x > 0 && filled(i - 1)) || (x < w - 1 && filled(i + 1)) ||
            (y > 0 && filled(i - w)) || (y < h - 1 && filled(i + w))) edges.push(i);
      }
    }
    const [r, g, b] = this.INK_RGB;
    for (const i of edges) { d[i * 4] = r; d[i * 4 + 1] = g; d[i * 4 + 2] = b; d[i * 4 + 3] = 255; }
    ctx.putImageData(img, 0, 0);
  },

  // grid: array of equal-ish length strings, '.' or ' ' = transparent.
  // Rendered with a 1px transparent pad + a uniform black outline.
  urlFromGrid(grid, pal = {}) {
    const key = grid.join('|') + '§' + JSON.stringify(pal);
    if (this._cache.has(key)) return this._cache.get(key);
    const h = grid.length;
    let w = 0;
    for (const row of grid) w = Math.max(w, row.length);
    const cv = document.createElement('canvas');
    cv.width = w + 2; cv.height = h + 2;
    const ctx = cv.getContext('2d');
    const colors = { ...this.BASE_PAL, ...pal };
    for (let y = 0; y < h; y++) {
      const row = grid[y];
      for (let x = 0; x < row.length; x++) {
        const ch = row[x];
        if (ch === '.' || ch === ' ') continue;
        ctx.fillStyle = colors[ch] || '#ff00ff';
        ctx.fillRect(x + 1, y + 1, 1, 1);
      }
    }
    this.outline(ctx, cv.width, cv.height);
    const url = cv.toDataURL();
    this._cache.set(key, url);
    return url;
  },

  // draw a grid onto an existing canvas ctx at offset (for compositing)
  drawGridOn(ctx, grid, pal = {}, ox = 0, oy = 0) {
    const colors = { ...this.BASE_PAL, ...pal };
    for (let y = 0; y < grid.length; y++) {
      const row = grid[y];
      for (let x = 0; x < row.length; x++) {
        const ch = row[x];
        if (ch === '.' || ch === ' ') continue;
        ctx.fillStyle = colors[ch] || '#ff00ff';
        ctx.fillRect(ox + x, oy + y, 1, 1);
      }
    }
  },

  img(url, size, cls = '', extra = '') {
    return `<img class="px ${cls}" src="${url}" style="width:${size}px" ${extra} alt="" draggable="false">`;
  },
};

/* ============================================================
   ICON ATLAS — 10x10-ish UI glyphs
   ============================================================ */
const ICONS = {

  /* ---------- currency / tray ---------- */
  coin: { p: { g: '#f0b541', d: '#c28024', l: '#ffe07a' }, g: [
    '...oooo...',
    '..ogggdo..',
    '.oglggggo.',
    'oglggoggdo',
    'oglgogogdo',
    'oglgogogdo',
    'oglggoggdo',
    '.ogggggdo.',
    '..ogddgo..',
    '...oooo...',
  ]},
  day: { p: { r: '#e6482e', c: '#f5efdf', d: '#cfc4ac' }, g: [
    '..o.....o.',
    '.ooooooooo',
    '.orrrrrrro',
    '.ooooooooo',
    '.occccccco',
    '.ocddcddco',
    '.occccccco',
    '.ocddcddco',
    '.occccccco',
    '.ooooooooo',
  ]},
  smiley: { p: { y: '#ffd93d', d: '#c28024' }, g: [
    '...oooo...',
    '..oyyyyo..',
    '.oyyyyyyo.',
    'oyyoyyoyyo',
    'oyyoyyoyyo',
    'oyyyyyyyyo',
    'oyoyyyyoyo',
    '.oyooooyo.',
    '..oyyyyo..',
    '...oooo...',
  ]},
  sound: { p: { b: '#7ec8ff' }, g: [
    '.....o....',
    '....oo..b.',
    '.oooko.b..',
    '.okkko..b.',
    '.okkko.b.b',
    '.okkko..b.',
    '.oooko.b..',
    '....oo..b.',
    '.....o....',
    '..........',
  ]},
  soundoff: { p: { r: '#e6482e' }, g: [
    '.....o....',
    '....oo....',
    '.oooko.r.r',
    '.okkko..r.',
    '.okkko.r.r',
    '.okkko....',
    '.oooko....',
    '....oo....',
    '.....o....',
    '..........',
  ]},
  music: { p: { b: '#8b7ce8' }, g: [
    '....obbbbo',
    '...obbbbbo',
    '...ob...bo',
    '...ob...bo',
    '...ob...bo',
    '.oobb..obb',
    'obbbb.obbb',
    'obbbb.obbb',
    '.obb...ob.',
    '..........',
  ]},

  /* ---------- desktop apps ---------- */
  dna: { p: { p: '#ff6ba9', c: '#4fc4e8' }, g: [
    '.pp....cc.',
    '.opp..cco.',
    '..oppcco..',
    '...oppo...',
    '...ocpo...',
    '..occpp o.',
    '.occ..ppo.',
    '.cc....pp.',
    '.occ..ppo.',
    '..occppo..',
  ]},
  swords: { p: { s: '#c8d0dd', h: '#a06a3c', l: '#f2f6fa' }, g: [
    'oss....sso',
    'oslo..olso',
    '.oslo.lso.',
    '..osloso..',
    '...osso...',
    '...osso...',
    '..ohooho..',
    '.oho..oho.',
    '.oo....oo.',
    '..........',
  ]},
  roster: { p: { c: '#f5efdf', b: '#4fc4e8' }, g: [
    'oooooo....',
    'occcco....',
    'ocbbcooooo',
    'occccccco.',
    'ocbbcbbco.',
    'occccccco.',
    'oooocbbco.',
    '...occcco.',
    '...oooooo.',
    '..........',
  ]},
  cart: { p: { y: '#f0b541' }, g: [
    'o.........',
    'oo........',
    '.ooooooooo',
    '.oyyyyyyo.',
    '..oyyyyo..',
    '..oyyyyo..',
    '..oooooo..',
    '..o....o..',
    '..oo...oo.',
    '..........',
  ]},
  bag: { p: { b: '#a06a3c', l: '#c98b52', s: '#f0b541' }, g: [
    '...oooo...',
    '..o....o..',
    '..o....o..',
    '.oobbbboo.',
    '.oblbbbbo.',
    '.oblbsbbo.',
    '.oblbbbbo.',
    '.obbbbbbo.',
    '..oooooo..',
    '..........',
  ]},
  grave: { p: { s: '#9a97b0', d: '#6f6c88', g: '#5fae5f' }, g: [
    '...oooo...',
    '..osssso..',
    '.osssssso.',
    '.osoossso.',
    '.oossssdo.',
    '.osoosddo.',
    '.ossssddo.',
    '.osssdddo.',
    'oooooooooo',
    'ggggggggg.',
  ]},
  doc: { p: { c: '#f5efdf', d: '#b9b2a0' }, g: [
    '.oooooo...',
    '.occccoo..',
    '.occccodo.',
    '.occoooco.',
    '.occcccco.',
    '.ocddddco.',
    '.occcccco.',
    '.ocddddco.',
    '.occcccco.',
    '.oooooooo.',
  ]},
  moon: { p: { y: '#ffe07a', d: '#f0b541' }, g: [
    '...ooooo..',
    '..oyyo....',
    '.oyyo.....',
    '.oydo.....',
    'oyyo......',
    'oyyo......',
    '.oydo.....',
    '.oyyoo..o.',
    '..oyyyyyo.',
    '...ooooo..',
  ]},
  reset: { p: { b: '#4fc4e8' }, g: [
    '..obbbbo..',
    '.obooobbo.',
    'obo...obbo',
    'obo....ooo',
    'obo...bbbb',
    'obo....bb.',
    'obo.....b.',
    '.obo..obo.',
    '..obbbbo..',
    '..........',
  ]},

  /* ---------- stats ---------- */
  heart: { p: { r: '#ff4d6d', l: '#ff8fa5' }, g: [
    '..........',
    '.oo...oo..',
    'orroo orro',
    'orlrrorrro',
    'orllrrrrro',
    '.orrrrrro.',
    '..orrrro..',
    '...orro...',
    '....oo....',
    '..........',
  ]},
  fist: { p: { s: '#f2b988', d: '#d99559' }, g: [
    '..........',
    '..oooooo..',
    '.osssssso.',
    '.osossoso.',
    'oossssssoo',
    'osdssssdso',
    'osssssssso',
    '.osssssso.',
    '..oossoo..',
    '..........',
  ]},
  brain: { p: { p: '#ff9ec4', d: '#e8709f' }, g: [
    '..oooooo..',
    '.oppoppdo.',
    'oppoppppdo',
    'opopopoddo',
    'oppoppoddo',
    'opopoppddo',
    '.oppopddo.',
    '..opdddo..',
    '...oodo...',
    '....oo....',
  ]},
  bolt: { p: { y: '#ffd93d', l: '#fff3a8' }, g: [
    '.....ooo..',
    '....oyyo..',
    '...oylyo..',
    '..oylyo...',
    '.oyyyyyoo.',
    '.ooooyyyo.',
    '...oyyoo..',
    '..oyyo....',
    '..oyo.....',
    '..oo......',
  ]},
  clover: { p: { g: '#5fae5f', l: '#8ed07f' }, g: [
    '.oo....oo.',
    'ollgoogllo',
    'olggggglgo',
    '.ogggggo..',
    'ogggggggo.',
    'olggggglgo',
    'ollgoogllo',
    '.oo.go.oo.',
    '....og....',
    '....og....',
  ]},
  star: { p: { y: '#ffd93d', l: '#fff3a8' }, g: [
    '....oo....',
    '...oyyo...',
    '...olyo...',
    'ooooyyoooo',
    'oyyyyyyyyo',
    '.oyyyyyyo.',
    '..oyyyyo..',
    '..oyooyo..',
    '.oyo..oyo.',
    '.oo....oo.',
  ]},
  boot: { p: { b: '#a06a3c', d: '#7c4f28' }, g: [
    '..........',
    '..oooo....',
    '..obbo....',
    '..obbo....',
    '..obbo....',
    '..obbooo..',
    '..obbbbbo.',
    '..obbbdbo.',
    '..oooooooo',
    '..........',
  ]},
  skull: { p: { c: '#f2f0f7', d: '#c9c4dd' }, g: [
    '..oooooo..',
    '.occcccco.',
    'occcccccco',
    'ocooccooco',
    'ocooccooco',
    'occcccccco',
    '.occococo.',
    '.odcocodo.',
    '..occcco..',
    '..........',
  ]},

  /* ---------- statuses ---------- */
  fire: { p: { r: '#e6482e', a: '#ff8a3d', y: '#ffd93d' }, g: [
    '....r.....',
    '....rr....',
    '...rar.r..',
    '..rraar...',
    '..raaaarr.',
    '.raayyaar.',
    '.rayyyyar.',
    '.rayyyyar.',
    '..rayyar..',
    '...rrrr...',
  ]},
  drop: { p: { g: '#7dc95e', d: '#4d9142' }, g: [
    '....o.....',
    '...ogo....',
    '...ogo....',
    '..oggdo...',
    '..oggdo...',
    '.ogggddo..',
    '.ogwggdo..',
    '.oggggdo..',
    '..ogddo...',
    '...ooo....',
  ]},
  dizzy: { p: { y: '#ffd93d', p: '#b98ae8' }, g: [
    '..o....o..',
    '.oyo..opo.',
    '..o....o..',
    '...oooo...',
    '..oppppo..',
    '.oppooppo.',
    '.opo..opo.',
    '.oppoppp..',
    '..opppo...',
    '...ooo....',
  ]},
  note: { p: { b: '#8b7ce8' }, g: [
    '....obbbbo',
    '....obbbbo',
    '....ob..bo',
    '....ob..bo',
    '....ob..bo',
    '..oobb.obb',
    '.obbbb.obb',
    '.obbbb..ob',
    '..obb.....',
    '..........',
  ]},
  hourglass: { p: { y: '#ffd93d', c: '#f5efdf' }, g: [
    '.oooooooo.',
    '..occcco..',
    '..oyyyyo..',
    '...oyyo...',
    '....oo....',
    '...ocyo...'.replace('y','c'),
    '..occcco..',
    '..oyyyyo..',
    '..oyyyyo..',
    '.oooooooo.',
  ]},
  arrowup: { p: { g: '#5fae5f', l: '#8ed07f' }, g: [
    '....oo....',
    '...olgo...',
    '..olggo...',
    '.olggggo..',
    'olgggggggo',
    'oooogggooo',
    '...oggo...',
    '...oggo...',
    '...oooo...',
    '..........',
  ]},
  arrowdown: { p: { r: '#e6482e', d: '#b53222' }, g: [
    '...oooo...',
    '...orro...',
    '...orro...',
    '...orro...',
    'ooorrrrooo',
    'orrrrrrrdo',
    '.orrrrrdo.',
    '..orrdo...',
    '...oo.....',
    '..........',
  ]},
  wind: { p: { c: '#7ec8ff' }, g: [
    '..........',
    '.occcco...',
    'o......o..',
    '..occcccco',
    '.o........',
    '...ccccco.',
    '..o.......',
    '.occcco...',
    '..........',
    '..........',
  ]},
  loop: { p: { c: '#4fc4e8' }, g: [
    '..occcco..',
    '.oco..oco.',
    'oco....occ',
    'oc.....ccc',
    'oc......c.',
    '.c......co',
    'ccc.....co',
    'cco....oco',
    '.oco..oco.',
    '..occcco..',
  ]},
  shield: { p: { b: '#4fc4e8', d: '#2f8cb3', l: '#a8e4f7' }, g: [
    '.oooooooo.',
    'oblbbbbbdo',
    'oblbbbbddo',
    'oblbbbbddo',
    'obbbbbbddo',
    '.obbbbddo.',
    '.obbbbddo.',
    '..obbddo..',
    '...obdo...',
    '....oo....',
  ]},
  virus: { p: { g: '#8ed07f', d: '#4d9142' }, g: [
    '.o..oo..o.',
    '..oggggo..',
    '.oggoogdo.',
    'ogggoogddo',
    'oggggggddo',
    'ogogggoddo',
    'oggogogddo',
    '.oggggddo.',
    '..oggddo..',
    '.o..oo..o.',
  ]},

  /* ---------- trait glyphs ---------- */
  weight: { p: { s: '#6f6c88', d: '#4c4963' }, g: [
    '..........',
    '.oo....oo.',
    'osso..osso',
    'ossoooosso',
    'osssssssso',
    'ossssssdso',
    'ossoooosso',
    'osso..osso',
    '.oo....oo.',
    '..........',
  ]},
  tape: { p: { k: '#26203a', c: '#4c4963', w: '#f5efdf' }, g: [
    '..........',
    'oooooooooo',
    'okkkkkkkko',
    'okwwkkwwko',
    'okwkkkkwko',
    'okwwkkwwko',
    'okkkkkkkko',
    'occcccccco',
    'oooooooooo',
    '..........',
  ]},
  sigma: { p: { s: '#c8d0dd' }, g: [
    '.oooooooo.',
    '.osssssso.',
    '.osoooooo.',
    '..osso....',
    '...osso...',
    '....oso...',
    '...osso...',
    '..osso....',
    '.osssssso.',
    '.oooooooo.',
  ]},
  halo: { p: { y: '#ffd93d', l: '#fff3a8' }, g: [
    '..oooooo..',
    '.oyyyyyyo.',
    'oyloooolyo',
    'oyo....oyo',
    'oyloooolyo',
    '.oyyyyyyo.',
    '..oooooo..',
    '..........',
    '..........',
    '..........',
  ]},
  snail: { p: { s: '#c98b52', b: '#8ed07f' }, g: [
    '..........',
    '..oooo....',
    '.osssso.o.',
    'ossooss.bo',
    'ossosss.bo',
    'ossoosso..',
    '.ossssobo.',
    'obbbbbbbo.',
    '.ooooooo..',
    '..........',
  ]},
  bread: { p: { b: '#e8b05c', d: '#c98b52', l: '#f7d08a' }, g: [
    '..........',
    '..oooooo..',
    '.ollllllo.',
    'olbbbbbblo',
    'obbdbbdbbo',
    'obbbbbbbbo',
    'obdbbdbbdo',
    'obbbbbbbbo',
    '.oooooooo.',
    '..........',
  ]},
  gritface: { p: { y: '#ffd93d' }, g: [
    '..oooooo..',
    '.oyyyyyyo.',
    'oyyoyyoyyo',
    'oyyoyyoyyo',
    'oyyyyyyyyo',
    'oyooooooyo',
    'oyoyoyoyyo',
    '.oyyyyyyo.',
    '..oooooo..',
    '..........',
  ]},
  chartdown: { p: { r: '#e6482e', c: '#f5efdf' }, g: [
    'oooooooooo',
    'occcccccco',
    'ocroccccco',
    'occrocccco',
    'occcrrocco',
    'occcccrrco',
    'occcccorro',
    'occcccrrro',
    'occcccccco',
    'oooooooooo',
  ]},
  egg: { p: { c: '#f5efdf', d: '#d8cfba' }, g: [
    '....oo....',
    '...occo...',
    '..occcco..',
    '.occcccdo.',
    '.owccccdo.',
    '.owcccddo.',
    '.occccddo.',
    '.occcdddo.',
    '..ocdddo..',
    '...oooo...',
  ]},
  npcface: { p: { s: '#c8d0dd' }, g: [
    '..oooooo..',
    '.osssssso.',
    'osssssssso',
    'ossossosso',
    'osssssssso',
    'osssssssso',
    'ossoooosso',
    '.osssssso.',
    '..oooooo..',
    '..........',
  ]},
  raincloud: { p: { s: '#9a97b0', b: '#7ec8ff' }, g: [
    '...oooo...',
    '..ossssoo.',
    '.ossssssso',
    'osssssssso',
    '.oooooooo.',
    '..b..b..b.',
    '.b..b..b..',
    '..b..b..b.',
    '..........',
    '..........',
  ]},
  cursor: { p: { c: '#f2f0f7' }, g: [
    '.o........',
    '.oo.......',
    '.oco......',
    '.occo.....',
    '.occco....',
    '.occcco...',
    '.occccco..',
    '.ocooooo..',
    '.oo.oco...',
    '.o...oo...',
  ]},
  eye: { p: { c: '#f2f0f7', r: '#b53222' }, g: [
    '..........',
    '...oooo...',
    '.oocccoo..',
    'occcrccco.',
    'occrrrcco.',
    'occcrccco.',
    '.oocccoo..',
    '...oooo...',
    '..........',
    '..........',
  ]},
  recycle: { p: { g: '#5fae5f' }, g: [
    '....og....',
    '...oggo...',
    '..og.ogo..',
    '.og...og..',
    'og.....og.',
    'ogo...ogo.',
    '.ogg.ogg..',
    '..og.og...',
    '...ogo....',
    '....o.....',
  ]},

  /* ---------- misc UI ---------- */
  lock: { p: { y: '#f0b541', d: '#c28024' }, g: [
    '...oooo...',
    '..oo..oo..',
    '..o....o..',
    '.oooooooo.',
    '.oyyyyyydo',
    '.oyyooyydo',
    '.oyyooyydo',
    '.oyyyoyydo',
    '.oyyyyyydo',
    '.oooooooo.',
  ]},
  check: { p: { g: '#5fae5f', l: '#8ed07f' }, g: [
    '..........',
    '........oo',
    '.......ogo',
    '......ogo.',
    'oo...oggo.',
    'ogo.oggo..',
    'oggoggo...',
    '.ogggo....',
    '..ogo.....',
    '...o......',
  ]},
  cross: { p: { r: '#e6482e' }, g: [
    '..........',
    '.oo....oo.',
    'orro..orro',
    '.orro.rro.',
    '..orrrro..',
    '..orrrro..',
    '.orro.rro.',
    'orro..orro',
    '.oo....oo.',
    '..........',
  ]},
  arrowleft: { p: { c: '#f2f0f7' }, g: [
    '..........',
    '...oo.....',
    '..oco.....',
    '.ocooooooo',
    'occcccccco',
    '.ocooooooo',
    '..oco.....',
    '...oo.....',
    '..........',
    '..........',
  ]},
  plus: { p: { g: '#5fae5f' }, g: [
    '..........',
    '...oooo...',
    '...oggo...',
    '.oooggooo.',
    '.oggggggo.',
    '.oggggggo.',
    '.oooggooo.',
    '...oggo...',
    '...oooo...',
    '..........',
  ]},
  warning: { p: { y: '#ffd93d' }, g: [
    '....oo....',
    '...oyyo...',
    '...oyyo...',
    '..oyooyo..',
    '..oyooyo..',
    '.oyyooyyo.',
    '.oyyyyyyo.',
    'oyyyooyyyo',
    'oyyyyyyyyo',
    '.oooooooo.',
  ]},
  gift: { p: { r: '#e6482e', y: '#ffd93d' }, g: [
    '.oo....oo.',
    'o..o..o..o',
    '.oooyyooo.',
    'orrryyrrro',
    'oyyyyyyyyo',
    'orrryyrrro',
    'orrryyrrro',
    'orrryyrrro',
    '.oooooooo.',
    '..........',
  ]},
  hand: { p: { s: '#f2b988', d: '#d99559' }, g: [
    '...o.o.o..',
    '..osososo.',
    '..osososo.',
    'o.ossssso.',
    'osossssss.',
    '.osssssso.',
    '.osssssso.',
    '..osssdo..',
    '..osssdo..',
    '...oooo...',
  ]},
  pencil: { p: { y: '#f0b541', s: '#f2b988', k: '#26203a' }, g: [
    '.......oo.',
    '......okko',
    '.....oyyko',
    '....oyyko.',
    '...oyyko..',
    '..oyyko...',
    '.oyyko....',
    '.osyo.....',
    '.oso......',
    '.oo.......',
  ]},
  sprout: { p: { g: '#5fae5f', l: '#8ed07f', b: '#a06a3c' }, g: [
    '..oo..oo..',
    '.olgooglo.',
    '.olggoggo.',
    '..oggggo..',
    '...oggo...',
    '....og....',
    '....og....',
    '..oooooo..',
    '..obbbbo..',
    '...oooo...',
  ]},
  wilt: { p: { r: '#c96a8a', g: '#8a915f' }, g: [
    '..oooo....',
    '.orrrro...',
    '.orrrro...',
    '..orro....',
    '...og.....',
    '....og....',
    '....og....',
    '...og.....',
    '..oooooo..',
    '..........',
  ]},
  window: { p: { b: '#4fc4e8', c: '#f5efdf' }, g: [
    'oooooooooo',
    'obbbbbbwbo',
    'oooooooooo',
    'occcccccco',
    'occcccccco',
    'occcccccco',
    'occcccccco',
    'occcccccco',
    'oooooooooo',
    '..........',
  ]},
  paw: { p: { s: '#f2b988' }, g: [
    '..........',
    '.oo....oo.',
    'osso..osso',
    'osso..osso',
    '.oo.oo.oo.',
    '..ossso...',
    '.ossssso..',
    '.ossssso..',
    '..ooooo...',
    '..........',
  ]},
  crosshair: { p: { r: '#e6482e' }, g: [
    '....oo....',
    '...orro...',
    '....oo....',
    '..o....o..',
    'oro.rr.oro',
    'oro.rr.oro',
    '..o....o..',
    '....oo....',
    '...orro...',
    '....oo....',
  ]},
};

const Icon = {
  has(name) { return !!ICONS[name]; },
  src(name) {
    const def = ICONS[name] || ICONS.star;
    return Pixel.urlFromGrid(def.g, def.p);
  },
  // inline <img> for template strings
  ico(name, size = 14, cls = '') {
    return Pixel.img(this.src(name), size, 'ico-px ' + cls);
  },
};
